language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - jruby-19mode # JRuby in 1.9 mode
  - ruby-head
  - jruby-head
  - rbx-2
env:
- COVERALLS=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
    - rvm: rbx-2
